table conflict_events
	lineageTag: 1fbf2592-8938-541c-b5e8-5a04f6b3190e

	column global_event_id
		dataType: int64
		formatString: 0
		lineageTag: f3bd0920-f197-5beb-a7b5-dfcee608d4c0
		summarizeBy: none
		sourceColumn: global_event_id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4aa1564e-c997-560e-8b3f-44fc3db2aac9
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hotspot_region
		dataType: string
		lineageTag: bea36ccd-0d27-563d-bf68-c15300c4c740
		summarizeBy: none
		sourceColumn: hotspot_region

		annotation SummarizationSetBy = Automatic

	column action_geo_name
		dataType: string
		lineageTag: 674bead6-440c-59c0-a7f6-7c795b26bfb8
		summarizeBy: none
		sourceColumn: action_geo_name

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: double
		lineageTag: 2fee1e23-9fb1-5746-80fb-4831f48f51e9
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: lat

		annotation SummarizationSetBy = Automatic

	column long
		dataType: double
		lineageTag: 22d91ea5-8ff2-593c-bfb7-593619682abc
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: long

		annotation SummarizationSetBy = Automatic

	column event_type
		dataType: string
		lineageTag: a80666da-9e03-5ecb-b953-68057143e985
		summarizeBy: none
		sourceColumn: event_type

		annotation SummarizationSetBy = Automatic

	column goldstein_scale
		dataType: double
		lineageTag: 9991c154-049d-5553-b2d3-e468c32901ce
		summarizeBy: none
		sourceColumn: goldstein_scale

		annotation SummarizationSetBy = Automatic

	column num_mentions
		dataType: int64
		formatString: 0
		lineageTag: 4130b526-1e65-5d33-9b71-83b0a0b6e3f0
		summarizeBy: none
		sourceColumn: num_mentions

		annotation SummarizationSetBy = Automatic

	column source_url
		dataType: string
		lineageTag: 50b2b4a8-3f17-5bf0-94b4-bac5fc6ab65d
		summarizeBy: none
		sourceColumn: source_url

		annotation SummarizationSetBy = Automatic

	partition conflict_events = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=conflict_events_live", [HierarchicalNavigation=true]),
				    conflict_events_Table = Source{[Name="conflict_events",Kind="Table"]}[Data],
				    #"Added Date" = Table.AddColumn(conflict_events_Table, "Date", each try #date(Number.FromText(Text.Start(Text.From([event_date]), 4)), Number.FromText(Text.Middle(Text.From([event_date]), 4, 2)), Number.FromText(Text.End(Text.From([event_date]), 2))) otherwise null, type nullable date),
				    // the price feeds start on 12 Aug 2026; earlier events would have no matching calendar day
				    #"Recent events" = Table.SelectRows(#"Added Date", each [Date] <> null and [Date] >= #date(2026, 8, 12)),
				    #"Added event type" = Table.AddColumn(#"Recent events", "event_type", each if [event_root_code] = "15" then "Show of force" else if [event_root_code] = "16" then "Reduced relations" else if [event_root_code] = "17" then "Coercion" else if [event_root_code] = "18" then "Assault" else if [event_root_code] = "19" then "Armed fight" else if [event_root_code] = "20" then "Mass violence" else "Other", type text),
				    #"Kept columns" = Table.SelectColumns(#"Added event type", {"global_event_id", "Date", "hotspot_region", "action_geo_name", "lat", "long", "event_type", "goldstein_scale", "num_mentions", "source_url"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Kept columns", {{"global_event_id", Int64.Type}, {"Date", type date}, {"hotspot_region", type text}, {"action_geo_name", type text}, {"lat", type number}, {"long", type number}, {"goldstein_scale", type number}, {"num_mentions", Int64.Type}, {"source_url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

